package sbnz.integracija;

import sbnz.integracija.example.model.Player

global String chosen;

rule "New player is Nord"
	when 
		$p: Player(race == "Nord")
	then
		chosen = "Nord";
		$p.setHeadStart("Two-handed", 25);
		$p.setPriority("Two-handed", 1);
		$p.setHeadStart("Smithing", 20);
		$p.setHeadStart("Block", 20);
		$p.setHeadStart("One-handed", 20);
		$p.setHeadStart("Light Armor", 20);
		$p.setHeadStart("Speech", 20);
		update($p);
end

rule "New player is Altmer"
	when 
		$p: Player(race == "Altmer")
	then
		chosen = "Altmer";
		$p.setHeadStart("Illusion", 25);
		$p.setPriority("Illusion", 1);
		$p.setHeadStart("Conjuration", 20);
		$p.setHeadStart("Destruction", 20);
		$p.setHeadStart("Restoration", 20);
		$p.setHeadStart("Alteration", 20);
		$p.setHeadStart("Enchanting", 20);
		update($p);
end

rule "New player is Argonian"
	when 
		$p: Player(race == "Argonian")
	then
		chosen = "Argonian";
		$p.setHeadStart("Lockpicking", 25);
		$p.setPriority("Lockpicking", 1);
		$p.setHeadStart("Sneak", 20);
		$p.setHeadStart("Restoration", 20);
		$p.setHeadStart("Alteration", 20);
		$p.setHeadStart("Light Armor", 20);
		$p.setHeadStart("Pickpocket", 20);
		update($p);
end

rule "New player is Bosmer"
	when 
		$p: Player(race == "Bosmer")
	then
		$p.setHeadStart("Archery", 25);
		$p.setPriority("Archery", 1);
		$p.setHeadStart("Sneak", 20);
		$p.setHeadStart("Pickpocket", 20);
		$p.setHeadStart("Alchemy", 20);
		$p.setHeadStart("Light Armor", 20);
		$p.setHeadStart("Lockpicking", 20);
		update($p);
		chosen = "Bosmer";
end

rule "New player is Breton"
	when 
		$p: Player(race == "Breton")
	then
		$p.setHeadStart("Conjuration", 25);
		$p.setPriority("Conjuration", 1);
		$p.setHeadStart("Alchemy", 20);
		$p.setHeadStart("Illusion", 20);
		$p.setHeadStart("Restoration", 20);
		$p.setHeadStart("Alteration", 20);
		$p.setHeadStart("Speech", 20);
		update($p);
		chosen = "Breton";
end

rule "New player is Dunmer"
	when 
		$p: Player(race == "Dunmer")
	then
		$p.setHeadStart("Destruction", 25);
		$p.setPriority("Destruction", 1);
		$p.setHeadStart("Alchemy", 20);
		$p.setHeadStart("Illusion", 20);
		$p.setHeadStart("Alteration", 20);
		$p.setHeadStart("Light Armor", 20);
		$p.setHeadStart("Sneak", 20);
		update($p);
		chosen = "Dunmer";
end

rule "New player is Imperial"
	when 
		$p: Player(race == "Imperial")
	then
		$p.setHeadStart("Restoration", 25);
		$p.setPriority("Restoration", 1);
		$p.setHeadStart("Enchanting", 20);
		$p.setHeadStart("Block", 20);
		$p.setHeadStart("One-handed", 20);
		$p.setHeadStart("Heavy Armor", 20);
		$p.setHeadStart("Destruction", 20);
		update($p);
		chosen = "Imperial";
end

rule "New player is Khajiit"
	when 
		$p: Player(race == "Khajiit")
	then
		$p.setHeadStart("Sneak", 25);
		$p.setPriority("Sneak", 1);
		$p.setHeadStart("Archery", 20);
		$p.setHeadStart("Lockpicking", 20);
		$p.setHeadStart("Pickpocket", 20);
		$p.setHeadStart("Alchemy", 20);
		$p.setHeadStart("Speech", 20);
		update($p);
		chosen = "Khajiit";
end

rule "New player is Orc"
	when 
		$p: Player(race == "Orc")
	then
		$p.setHeadStart("Heavy Armor", 25);
		$p.setPriority("Heavy Armor", 1);
		$p.setHeadStart("Block", 20);
		$p.setHeadStart("Enchanting", 20);
		$p.setHeadStart("Smithing", 20);
		$p.setHeadStart("One-handed", 20);
		$p.setHeadStart("Two-handed", 20);
		update($p);
		chosen = "Orc";
end

rule "New player is Redguard"
	when 
		$p: Player(race == "Redguard")
	then
		$p.setHeadStart("One-handed", 25);
		$p.setPriority("One-handed", 1);
		$p.setHeadStart("Archery", 20);
		$p.setHeadStart("Block", 20);
		$p.setHeadStart("Smithing", 20);
		$p.setHeadStart("Destruction", 20);
		$p.setHeadStart("Alteration", 20);
		update($p);
		chosen = "Redguard";
end
